export const HOME = '/'
export const ADMIN = '/admin'
export const APPLY = '/applicants/apply'
export const STAKE = '/verifiers/stake'
export const VERIFY = '/verifiers/verify'
export const WALLET = '/wallet'
