export const HOME = '/'
export const REGISTRY = '/registry/:currentPage'
export const ADMIN = '/admin'
export const REGISTER_TOKEN = '/applicants/register'
export const STAKE = '/verifiers/stake'
export const VERIFY = '/verifiers/verify'
export const VERIFY_APPLICATION = '/verifiers/verify/:applicationId'
export const WALLET = '/wallet'
