export const HOME = '/'
export const LISTINGS = '/listings/:currentPage'
export const ADMIN = '/admin'
export const APPLY = '/applicants/apply'
export const STAKE = '/verifiers/stake'
export const VERIFY = '/verifiers/verify'
export const VERIFY_APPLICATION = '/verifiers/verify/:applicationId'
export const WALLET = '/wallet'
